#! /bin/sh
echo "Setting static route for private network"
t=$(date)
echo "Delay 1m from now " $t
NETWORK=0.0.0.0/24
GATEWAY=0.0.0.0
sleep 60 && /sbin/route -n add $NETWORK $GATEWAY
t=$(date)
echo "Exiting /scripts/addroutes " $t
